### ISSUE TITLE
Database missing

### ISSUE THREAD

**Issue by joaoescribano** [ProfessorJamesBach/Inys#2]
I've tried to test the source but seems like the folder that contains the database backup (**inys_db**) wasn't available.
----
Estava tentando rodar o codigo mas a pasta que contem o database esta faltando (**inys_db**)

**Comment by DioxideHydrogen** [comment]
> 
> ## I've tried to test the source but seems like the folder that contains the database backup (**inys_db**) wasn't available.
> 
> Estava tentando rodar o codigo mas a pasta que contem o database esta faltando (**inys_db**)

Added thanks :v:, please look the new README, the name of databafe need be alexa_db

**Comment by joaoescribano** [comment]
Thanks!
